config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :exports, only: [:index] do
      collection do
        get :attendances
      end
    end
  end


  resources :attendances do
  collection do
    post :bulk_update
  end
end




  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'pages#home'
  resources :trainings do
    resources :attendances, only: [:index, :show, :new, :create, :update, :edit]
    resources :pre_training_evaluations, only: [:index, :show, :new, :create]
    resources :after_training_evaluations, only: [:index, :show, :new, :create]
  end
  resources :player_profils
  # resources :users do
  #   resources :job_load_evaluations, only: [:new, :create, :show]
  # end
  resources :job_load_evaluations, only: [:index, :show, :new, :create]
  resources :match_performances, only: [:index, :show, :new, :create, :update, :edit]
  # config/routes.rb
  devise_scope :user do
    get   'user/edit_avatar',   to: 'users/registrations#edit_avatar',   as: :edit_avatar_user
    patch 'user/update_avatar', to: 'users/registrations#update_avatar', as: :update_avatar_user
  end

end

app/models/training.rb
# © 2025 Violaine Soulas Tous droits réservés.
#  Propriété exclusive de Violaine Soulas.
#  Toute reproduction, même partielle, est interdite sans l'autorisation écrite de Violaine Soulas.
class Training < ApplicationRecord
  has_many :pre_training_evaluations
  has_many :after_training_evaluations

  has_many :users, through: :pre_training_evaluations
  has_many :users, through: :after_training_evaluations

  has_many :attendances, dependent: :destroy

  def prepa_materiel
    present_players = attendances.includes(:user).where(status: :present).map(&:user).uniq

    selected_players = present_players.sample(6)

    selected_players.map do |player|
      player.player_profil&.full_name || player.name # fallback si pas de profil
    end.join(", ")
  end

     # Appelée après la création des présences
  def generate_player_material_list
    update(player_material_list: prepa_materiel)
  end


end

app/controllers/trainings_controller.rb
# © 2025 Violaine Soulas Tous droits réservés.
#  Propriété exclusive de Violaine Soulas.
#  Toute reproduction, même partielle, est interdite sans l'autorisation écrite de Violaine Soulas.


class TrainingsController < ApplicationController


  before_action :authenticate_user!
  before_action :set_training, only: [:show, :edit, :update, :destroy]
  after_action :verify_policy_scoped, only: :index  # Vérifie la politique du scope pour l'index

  def index
    @trainings = policy_scope(Training)

  end

  def show
    @training = Training.includes(attendances: { user: :player_profil }).find(params[:id])
    authorize @training

    # Tous les joueurs (peut être filtrés selon ta logique métier)
    @players = User.joins(:player_profil)
               .where(role: 'joueur')
               .order('player_profils.last_name')
               .includes(:player_profil)


    # Attendances existantes indexées par user_id
    @attendances = @training.attendances.index_by(&:user_id)

    if current_user.joueur?
      @pre_training_evaluation = PreTrainingEvaluation.find_by(training: @training, user: current_user)
    elsif current_user.entraineur?
      @pre_training_evaluations = PreTrainingEvaluation.includes(:user).where(training: @training)
    end

    if current_user.joueur?
      @after_training_evaluation = AfterTrainingEvaluation.find_by(training: @training, user: current_user)
    elsif current_user.entraineur?
      @after_training_evaluations = AfterTrainingEvaluation.includes(:user).where(training: @training)
    end
  end

  def new
    @training = Training.new
    authorize @training
  end

  def create
    @training = Training.new(training_params)
    authorize @training
    if @training.save
       players = User.joins(:player_profil)
                  .where(role: 'joueur')
                  .order('player_profils.last_name ASC, player_profils.first_name ASC')

      redirect_to @training, notice: 'Entraînement créé avec succès.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @training
  end

  def update
    authorize @training

    if @training.update(training_params)
      redirect_to @training, notice: 'Entraînement mis à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    authorize @training
    @training.destroy
    redirect_to trainings_path, notice: 'Entraînement supprimé avec succès.', status: :see_other
  end

  private
  def training_params
    params.require(:training).permit(:date, :title, :location, :description, :start_time, :end_time)
  end
  def set_training
    @training = Training.find(params[:id])
  end
end

app/views/trainings/_form-training.html.erb
<div class="container">
  <div class="form-training">
    <div class="row d-flex justify-content-center">
      <div class="col-10 col-md-8 col-md-6">
        <h2 class="mt-5 text-center">Nouvel entraînement</h2>
          <%= simple_form_for @training do |f| %>
            <div class="form-inputs">
              <%= f.input :date, as: :string,
                label: "Date de l'entraînement",
                          input_html: { data: { controller: "datepicker" }} %>
              <%= f.input :start_time, as: :time, label: "Heure de début", class:"text-dark" %>
              <%= f.input :end_time, as: :time, label: "Heure de fin" %>


              <%= f.input :title, label:"Nom de l'entraînement" %>
              <%= f.input :location, label: "Lieu" %>
              <%= f.input :description %>
            </div>

            <div class="form-actions">
              <%= f.button :submit, "Créer l'entraînement", class: "btn btn-primary text-white" %>
            </div>
         <% end %>
        <div class="mt-5">
        <p><%= link_to "Retour", trainings_path, class:"btn btn-secondary" %></p>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/trainings/edit.html.erb
<div class="container mt-5">
  <%= render  'form-training', training: @training %>
</div>

app/views/trainings/index.html.erb
<%# app/views/trainings/index.html.erb %>
<div class="container mt-5">
  <% if current_user.entraineur? %>
    <div class="text-end mb-4">
      <%= link_to "Créer un entraînement", new_training_path, class: "btn-add text-white text-end" %>
    </div>
  <% end %>

  <h1 class="my-4 text-center">Entraînements</h1>

  <div class="training-grid">
    <% @trainings.each do |t| %>
      <% past = (t.date < Date.current) %>
      <%= link_to training_path(t),
                  class: "training-square #{'past' if past}" do %>
        <div class="day-number"><%= t.date.day %></div>
        <div class="month-abbrev"><%= l t.date, format: "%b", locale: :fr %></div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/trainings/new.html.erb
<div class="container">
  <%= render 'form-training' %>
</div>

app/views/trainings/show.html.erb
<div class="container">

 <div class="training-joueur d-flex justify-content-center">

    <div class="training-details">
      <p><i class="fa-solid fa-calendar-days me-2 text-dark "></i><strong><%= @training.date.strftime("%d/%m/%Y")%></strong></p>
      <% if @training.title.present?%>
        <strong><p> <%= @training.title%></p></strong>
      <% end %>
      <% if @training.location.present? %>
        <p> <i class="fa-solid fa-location-dot me-2 text-dark"></i><%= @training.location %></p>
      <% end %>
      <p><i class="fa-solid fa-clock me-2 text-dark"></i>
        <%= @training.start_time.strftime("%H:%M") %> - <%= @training.end_time.strftime("%H:%M") %>
      </p>

      <% if @training.description.present? %>
        <p><%= @training.description%></p>
      <% end %>

        <div class="text-end">
              <% if policy(Training).create?%>
                    <%= link_to edit_training_path do %>
                    <i class="fa-solid fa-pen-to-square text-dark"></i>
                  <% end %>
                <% end %>
                  <% if policy(Training).destroy? %>
                    <%= link_to training_path, data: { turbo_method: :delete, turbo_confirm: "ES-tu sûr ?" } do %>
                      <i class="fa-solid fa-trash text-dark"></i>
                    <% end %>
                <% end %>
        </div>
    </div>
  </div>

  <div class="row d-flex justify-content-center">
    <div class="col-sm-10 col-md-6 col-lg-4 mx-auto">
      <div class="evaluations">
    <% if current_user.joueur? %>
      <% if @pre_training_evaluation %>
        <div class=".training-joueur mt-5">
          <h4>Ton évaluation pré-entrainement</h4>
          <ul>
            <li>Fatigue cognitive : <%= @pre_training_evaluation.cognitive_fatigue %> / 5</li>
            <li>Fatigue physique : <%= @pre_training_evaluation.physical_fatigue %> / 5</li>
            <li>Humeur : <%= @pre_training_evaluation.mood %> / 5</li>
          </ul>
        </div>
      <% else %>
        <%= link_to "Faire mon évaluation pré-entrainement", new_training_pre_training_evaluation_path(@training), class: "btn btn-primary fs-4 text-white mt-3" %>
      <% end %>
      <% if @after_training_evaluation.present? %>
        <div class=" training-joueur mt-5">
          <h4>Ton évaluation post-entrainement</h4>
          <ul>
            <li>Intensité de l'entraînement : <%= @after_training_evaluation.after_intensity %></li>
            <li>Fatigue physique : <%= @after_training_evaluation.after_fatigue %></li>
            <li>Plaisir de l'entraînement : <%= @after_training_evaluation.pleasure ? "Oui" : "Non" %></li>
          </ul>
        </div>
        <% else %>
          <%= link_to "Faire mon évaluation post-entrainement", new_training_after_training_evaluation_path(@training), class: "btn btn-primary fs-4 text-white mt-3" %>
        <% end %>
    <% end %>
  </div>


  </div>
</div>


    <% if current_user.entraineur? %>
      <div class="mt-5">
        <h4>Évaluations pré-entrainement des joueurs</h4>
        <div class="row d-flex justify-content-center">
          <div class="col-sm-12 col-md-12 col-lg-12 mx-auto">
            <table class="table table-bordered">
              <thead>
                <tr class="text-center">
                  <th class="text-center">Joueur</th>
                  <th class="text-center">Fatigue cognitive</th>
                  <th class="text-center">Fatigue physique</th>
                  <th class="text-center" >Humeur</th>
                </tr>
              </thead>
              <tbody>
                <% @pre_training_evaluations.sort_by { |e| e.user.player_profil.last_name.to_s.downcase }.each do |evaluation| %>
                  <tr>
                    <td><%= "#{evaluation.user.player_profil.last_name} #{evaluation.user.player_profil.first_name}" %></td>
                    <td><%= evaluation.cognitive_fatigue %> /5</td>
                    <td><%= evaluation.physical_fatigue %> /5</td>
                    <td><%= evaluation.mood %> /5</td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="row d-flex justify-content-center">
          <div class="col-sm-12 col-md-12 col-lg-12 mx-auto">
            <div class="mt-5">
            <h4>Évaluations post-entrainement des joueurs</h4>
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th class="text-center">Joueur</th>
                    <th class="text-center">Intensité de l'entraînement</th>
                    <th class="text-center">Fatigue physique</th>
                    <th class="text-center">Plaisir à l'entraînement</th>
                  </tr>
                </thead>
                <tbody>
                  <% @after_training_evaluations.sort_by { |e| e.user.player_profil.last_name.to_s.downcase }.each do |evaluation| %>

                    <tr>
                      <td><%= "#{evaluation.user.player_profil.first_name} #{evaluation.user.player_profil.last_name}" %></td>
                      <td><%= evaluation.after_intensity %></td>
                      <td><%= evaluation.after_fatigue %></td>
                      <td><%= evaluation.pleasure ? "Oui" : "Non" %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
          </div>
        <% end %>
      </div>
    </div>
  </div>


 <div class="my-5">
  <% if current_user.entraineur? %>
    <h4>Absences / Retards des joueurs</h4>

  <div class="d-flex justify-content-center mt-3  align-items-center border border-1 border-white p-3">
    <p><strong class="text-white d-flex align_items-center me-3"> <i class="fa-solid fa-futbol me-2 fs-4"></i> Joueurs désignés pour le matériel </strong></p>
    <p><%= @training.player_material_list.presence || "Non encore générée" %></p>
  </div>



    <table class="table table-striped mt-3">
      <thead>
        <tr>
          <th>Joueur</th>
          <th>Date</th>
          <th class="text-center">Statut</th>
        </tr>
      </thead>
      <tbody>
        <% @training.attendances.sort_by { |a| a.user.player_profil&.last_name.to_s.downcase }.each do |a| %>
          <tr>
            <td><%= "#{a.user.player_profil.last_name} #{a.user.player_profil.first_name}" %></td>
            <td><%= a.training.date.strftime("%d/%m/%Y") %></td>
            <td class="text-center">
              <% badge_class = case a.status
                  when "present" then "badge bg-success"
                  when "absent" then "badge bg-danger"
                  when "late" then "badge bg-warning text-dark"
                  when "excused" then "badge bg-info text-dark"
                  else "badge bg-secondary"
                end %>
              <span class="<%= badge_class %>">
                <%= a.status.present? ? a.status.capitalize : "Non défini" %>
              </span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<% if current_user.entraineur? %>
<div class="row d-flex justify-content-center">
  <div class="col-sm-8 col-md-8 col-lg-6 mx-auto ">
      <h4 class="text-center mb-3">Saisie</h4>
      <%= form_with url: bulk_update_attendances_path, method: :post do %>

      <%= hidden_field_tag :training_id, @training.id %>

        <table id="attendance-table" class="table table-striped mt-3">
          <thead>
            <tr>
              <th>Joueur</th>
              <th>Statut</th>
              <th>Statut actuel</th>
            </tr>
          </thead>
          <tbody>
            <% @players.each do |player| %>
              <% attendance = @attendances[player.id] %>
              <tr class="text-dark">
                <td>
                  <%= player.player_profil ? "#{player.player_profil.last_name} #{player.player_profil.first_name}" : "" %>
                </td>
                <td class="text-dark">
                  <%= select_tag "attendances[#{player.id}][status]", options_for_select(['present', 'absent', 'late', 'excused'], attendance&.status), include_blank: true, prompt:"Séléctionner", class:"form-select status-select"%>
                </td>
                <td>
                  <% if attendance %>
                    <% badge_class = case attendance.status
                                    when "present" then "badge bg-success"
                                    when "absent" then "badge bg-danger"
                                    when "late" then "badge bg-warning text-dark"
                                    when "excused" then "badge bg-info text-dark"
                                    else "badge bg-secondary"
                                  end %>
                    <span class="<%= badge_class %>">
                      <%= attendance.status.present? ? attendance.status.capitalize : "Non défini" %>
                    </span>
                  <% else %>
                    <span class="badge bg-secondary">Non défini</span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

      <%= submit_tag "Enregistrer", class:"btn btn-add" %>
    <% end %>
  <% end %>
    </div>
  </div>
</div>