config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :exports, only: [:index] do
      collection do
        get :attendances
      end
    end
  end


  resources :attendances do
  collection do
    post :bulk_update
  end
end




  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'pages#home'
  resources :trainings do
    resources :attendances, only: [:index, :show, :new, :create, :update, :edit]
    resources :pre_training_evaluations, only: [:index, :show, :new, :create]
    resources :after_training_evaluations, only: [:index, :show, :new, :create]
  end
  resources :player_profils
  # resources :users do
  #   resources :job_load_evaluations, only: [:new, :create, :show]
  # end
  resources :job_load_evaluations, only: [:index, :show, :new, :create]
  resources :match_performances, only: [:index, :show, :new, :create, :update, :edit]
  # config/routes.rb
  devise_scope :user do
    get   'user/edit_avatar',   to: 'users/registrations#edit_avatar',   as: :edit_avatar_user
    patch 'user/update_avatar', to: 'users/registrations#update_avatar', as: :update_avatar_user
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% if current_user %>
  <div class="footer d-flex justify-content-around align-items-center">

      <%= link_to root_path,  class: "nav-link #{'active' if current_page?(root_path)}"  do %>
        <i class="fa-solid fa-house fs-2 "></i>Accueil
      <% end %>



      <%= link_to trainings_path,  class: "nav-link #{'active' if current_page?(trainings_path)}" do %>
        <i class="fa-solid fa-person-running fs-2 "></i>Entraînements
      <% end %>



      <%= link_to match_performances_path,  class: "nav-link #{'active' if current_page?(match_performances_path)}" do %>
        <i class="fa-solid fa-futbol fs-2 "></i>Matchs
      <% end %>



      <% if current_user.entraineur? %>
        <%= link_to player_profils_path,  class: "nav-link #{'active' if current_page?(player_profils_path)}" do %>
          <i class="fa-solid fa-people-group fs-2 "></i>Joueurs
        <% end %>
      <% elsif current_user.player_profil.present? %>
        <%= link_to player_profil_path(current_user.player_profil), class: "nav-link #{'active' if current_page?(player_profil_path(current_user.player_profil))}" do %>
          <i class="fa-solid fa-user fs-2 "></i>Profil
        <% end %>
      <% end %>

  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link  rel= "apple-touch-icon"  sizes= "57x57"  href= "/apple-icon-57x57.png" >
<link  rel= "apple-touch-icon"  sizes= "60x60"  href= "/apple-icon-60x60.png" >
<link  rel= "apple-touch-icon"  sizes= "72x72"  href= "/apple-icon-72x72.png" >
<link  rel= "apple-touch-icon"  sizes= "76x76"  href= "/apple-icon-76x76.png" >
<link  rel= "apple-touch-icon"  sizes= "114x114"  href= "/apple-icon-114x114.png" >
<link  rel= "apple-touch-icon"  sizes= "120x120"  href= "/apple-icon-120x120.png" >
<link  rel= "apple-touch-icon"  sizes= "144x144"  href= "/apple-icon-144x144.png" >
<link  rel= "apple-touch-icon"  sizes= "152x152"  href= "/apple-icon-152x152.png" >
<link  rel= "apple-touch-icon"  sizes= "180x180"  href= "/apple-icon-180x180.png" >
<link  rel= "icon"  type= "image/png"  sizes= "192x192"   href= "/android-icon-192x192.png" >
<link  rel= "icon"  type= "image/png"  sizes= "32x32"  href= "/favicon-32x32.png" >
<link  rel= "icon"  type= "image/png"  sizes= "96x96"  href= "/favicon-96x96.png" >
<link  rel= "icon"  type= "image/png"  sizes= "16x16"  href= "/favicon-16x16.png" >
<link  rel= "manifest"  href= "/manifest.json" >
<meta  name= "msapplication-TileColor"  content= "#ffffff" >
<meta  name= "msapplication-TileImage"  content= "/ms-icon-144x144.png" >
<meta  name= "theme-color"  content= "#ffffff" >

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex align-items-center">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <% if user_signed_in? %>
        <%= image_tag "club-logo.webp", class: "rounded-circle", size: "50x50" %>
      <% end %>
    </div>

    <div class="nom">
      <h1 class="text-dark" id="nom">CoachLead</h1>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>

          <li class="nav-item dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
              data-bs-toggle="dropdown" aria-expanded="false">
              Mon compte
            </button>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
              <% if current_user.entraineur?%>
              <li><%= link_to "Exporter des données", admin_exports_path, class:"dropdown-item text-dark"%></li>
              <% end %>
              <li><%= link_to 'Modifier mon compte', edit_user_registration_path, class: "dropdown-item text-dark" %></li>
              <li><%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item text-dark" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>