config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :exports, only: [:index] do
      collection do
        get :attendances
      end
    end
  end


  resources :attendances do
  collection do
    post :bulk_update
  end
end




  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'pages#home'
  resources :trainings do
    resources :attendances, only: [:index, :show, :new, :create, :update, :edit]
    resources :pre_training_evaluations, only: [:index, :show, :new, :create]
    resources :after_training_evaluations, only: [:index, :show, :new, :create]
  end
  resources :player_profils
  # resources :users do
  #   resources :job_load_evaluations, only: [:new, :create, :show]
  # end
  resources :job_load_evaluations, only: [:index, :show, :new, :create]
  resources :match_performances, only: [:index, :show, :new, :create, :update, :edit]
  # config/routes.rb
  devise_scope :user do
    get   'user/edit_avatar',   to: 'users/registrations#edit_avatar',   as: :edit_avatar_user
    patch 'user/update_avatar', to: 'users/registrations#update_avatar', as: :update_avatar_user
  end

end

app/models/player_profil.rb
# © 2025 Violaine Soulas Tous droits réservés.
#  Propriété exclusive de Violaine Soulas.
#  Toute reproduction, même partielle, est interdite sans l'autorisation écrite de Violaine Soulas.
class PlayerProfil < ApplicationRecord

  belongs_to :user
  before_destroy :destroy_user_related_records
  has_one_attached :photo

  # validations
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :weight, numericality: { greater_than_or_equal_to: 30 }, allow_nil: true
  validates :children_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  include PgSearch::Model
  pg_search_scope :search_by_first_and_last_name,
    against: [:first_name, :last_name],
    using: {
      tsearch: { prefix: true } # Permet la recherche par préfixe
    }

  def destroy_user_related_records
    return unless user.present?

    user.attendances.destroy_all
    user.job_load_evaluations.destroy_all
    user.match_performances.destroy_all
    user.pre_training_evaluations.destroy_all
    user.after_training_evaluations.destroy_all
  end

  def full_name
    "#{first_name} #{last_name}"
  end

    def total_penalties
    user.attendances
        .where(status: [:absent, :late, :excused])
        .count
  end

  # Montant total en euros (1€ par pénalité)
  def total_penalties_amount
    total_penalties
  end

  def self.average_penalties
    profils = all # Pas d'includes ici
    total = profils.map(&:total_penalties).sum
    count = profils.size
    return 0 if count == 0
    (total.to_f / count).round(2)
  end

  def age
    return nil unless date_of_birth.present?

    today = Date.today
    age = today.year - date_of_birth.year
    age -= 1 if today < date_of_birth + age.years # Ajustement si l'anniversaire n'est pas encore passé cette année
    age
  end

  def birthday_today?
    return false unless date_of_birth.present?

    today = Date.today
    today.day == date_of_birth.day && today.month == date_of_birth.month
  end

end

app/controllers/player_profils_controller.rb
# © 2025 Violaine Soulas Tous droits réservés.
#  Propriété exclusive de Violaine Soulas.
#  Toute reproduction, même partielle, est interdite sans l'autorisation écrite de Violaine Soulas.
class PlayerProfilsController < ApplicationController
  before_action :set_player_profil, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  after_action :verify_policy_scoped, only: :index  # Vérifie la politique du scope pour l'index
  before_action :authorize_user, only: :index  # Vérifie l'autorisation d'accès à l'index

  def index
      @player_profils = policy_scope(PlayerProfil).includes(photo_attachment: :blob)
      if params[:query].present?
        @player_profils = @player_profils.search_by_first_and_last_name(params[:query])
      end
      @player_profils = @player_profils.order(:last_name)
  end

  def show
    authorize @player_profil
  end

  def new
    @player_profil = PlayerProfil.new
    authorize @player_profil

  end

  def create
    @player_profil = PlayerProfil.new(player_profil_params)
    authorize @player_profil


    unique_email = "provisoire+#{SecureRandom.hex(3)}@example.com"
    common_password=ENV.fetch("COMMON_PASSWORD")
    first_name = params.dig(:player_profil, :first_name).to_s.downcase.strip
    last_name  = params.dig(:player_profil, :last_name).to_s.downcase.strip

    base_pseudo = "#{first_name}-#{last_name}".gsub(/\s+/, "_")
    pseudo = generate_unique_pseudo(base_pseudo)


    user = User.new(
      email: unique_email,
      password: common_password,
      password_confirmation: common_password,
      pseudo: pseudo,
      role: "joueur"
    )

    if user.save
      @player_profil = user.build_player_profil(player_profil_params)

      if @player_profil.save
        redirect_to @player_profil, notice: "Profil et utilisateur créés avec succès."
      else
        user.destroy
        puts @player_profil.errors.full_messages
        render :new, status: :unprocessable_entity
      end
    else
      puts user.errors.full_messages
      render :new, status: :unprocessable_entity
    end

  end

  def edit
    authorize @player_profil
  end

  def update
    authorize @player_profil
    if @player_profil.update(player_profil_params)
      redirect_to @player_profil, notice: 'Profil du joueur mis à jour'
    else
      render :edit
    end
  end

  def destroy
    authorize @player_profil
    @player_profil.destroy
    redirect_to player_profils_url, notice: 'Profil du joueur supprimé.', status: :see_other
  end

  private
  def set_player_profil
    @player_profil = PlayerProfil.includes(user: { attendances: :training }).find(params[:id])
  end

  def player_profil_params
    params.require(:player_profil).permit(:age, :weight, :children_count, :job, :photo, :first_name, :last_name, :date_of_birth, :vma)
  end

  def authorize_user
    # Vérifie si l'utilisateur connecté est un 'entraineur'
    authorize :player_profil, :index?  # Cela utilise la politique définie dans PlayerProfilPolicy
  end

  def generate_unique_pseudo(base)
  pseudo = base
  count = 1

  while User.exists?(pseudo: pseudo)
    pseudo = "#{base}_#{count}"
    count += 1
  end

  pseudo
end
end

app/views/player_profils/_form.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-8 col-sm-6 col-md-6 col-lg-6 ">
       <h2 class="text-center">Nouveau joueur</h2>
      <div class="new-player-profil">
        <div class="form-player-profil">
            <%= simple_form_for(@player_profil, html: { multipart: true }) do |f| %>
            <%= f.input :last_name,     as: :string, label: "Nom" %>
            <%= f.input :first_name,    as: :string, label: "Prénom" %>
            <%= f.input :photo,
                        as: :file,
                        input_html: { class: 'd-none' },
                        label_html: { class: 'upload-photo' },
                        label: '📷 Télécharge une photo' %>

            <div class="field">
              <%= f.label :date_of_birth, "Date de naissance" %>
              <%= f.text_field :date_of_birth, type: 'date', class: 'form-control' %>
            </div>



            <%= f.input :weight,          label: "Poids (kg)" %>
            <%= f.input :vma, label: "VMA "%>
            <%= f.input :job,            as: :string, label: "Activité professionnelle" %>
            <%= f.input :children_count,  label: "Nombre d'enfants" %>

            <%= f.button :submit, "Créer/Modifier le profil", class: 'btn-new-joueur mb-3' %>
            <% end %>

        </div>
      </div>
      <div class="mb-4">
          <%= link_to "Retour aux joueurs", player_profils_path, class:"btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/player_profils/edit.html.erb
<%= render 'form', player_profil: @player_profil %>

app/views/player_profils/index.html.erb
<div class="container mt-5">
  <div class="text-end">
    <%= link_to "Ajouter un profil", new_player_profil_path, class: "btn-add text-white text-end" %>
  </div>
  <div class="row mt-5 d-flex justify-content-center">
    <div class="col-sm-6 col-md-4 col-lg-4">

        <%= form_with url: player_profils_path, method: :get, local: true, class:"d-flex justify-content-center" do %>
          <%= text_field_tag :query, params[:query], class: "form-control me-2", placeholder: "Rechercher un joueur", onclick: "this.value=''" %>
          <button type="submit" class="btn btn-secondary" title="Rechercher un joueur">
            <i class="fa-solid fa-magnifying-glass"></i>
          </button>
        <% end %>

    </div>
  </div>

  
  <div class="row mt-5">
    <% if @player_profils.present? %>
      <% @player_profils.each do |player| %>
        <div class="col-12 col-sm-6 col-md-2col-lg-3 mb-4 d-flex justify-content-center">
          <%= link_to player_profil_path(player), class: "text-decoration-none text-dark" do %>
            <div class="card h-100 shadow-sm" style="width: 100%; max-width: 300px;">
              <% if player.photo.attached? %>
                <%= cl_image_tag player.photo.key, width: 250, height: 170, crop: :fill, gravity: :auto, class: "card-img-top", alt: "Photo du joueur" %>
              <% else %>
                <i class="fa-solid fa-circle-user fa-5x my-3 d-block mx-auto"></i>
              <% end %>
              <div class="card-body text-center">
                <h5 class="card-title"><strong><%= player.last_name %> <%= player.first_name%> </strong></h5>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <div class="text-center">
        <p><em>Aucun profil de joueur pour le moment </em></p>
      </div>
    <% end %>
  </div>

</div>

app/views/player_profils/new.html.erb
<%= render 'form' %>

app/views/player_profils/show.html.erb
<div class="container">
  <div class="text-end mt-3 fs-4">
     <% if policy(PlayerProfil).create? %>
      <%= link_to edit_player_profil_path(@player_profil) do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
    <% end %>

    <% if policy(PlayerProfil).destroy? %>
      <%= link_to player_profil_path(@player_profil), data: { turbo_method: :delete, turbo_confirm: "Es-tu sûr?" } do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
    <% end %>
  </div>

  <h1 class="text-center mt-3" id="player-profil-fullname">
    <strong class="text-white"><%= @player_profil.full_name %></strong>
  </h1>

  <div class="details-player-profil">
    <div class="player-card-show">
      <% if @player_profil.photo.attached? %>
        <%= cl_image_tag @player_profil.photo.key,
              width: 300,
              height: 250,
              crop: "fill",
              gravity: "face",
              fetch_format: "auto",
              quality: "auto",
              class: "card-img-top",
              alt: "Photo du joueur",
              style: "object-fit:cover;" %>
      <% else %>
        <i class="fa-solid fa-circle-user fa-5x my-3 d-block mx-auto text-dark"></i>
      <% end %>

      <% if current_user.entraineur? %>
        <%= link_to edit_player_profil_path(@player_profil) do %>
          <i class="fa-regular fa-pen-to-square text-dark"></i>
        <% end %>
      <% end %>
    </div>

    <div class="player-card-show">
      <p><strong><%= @player_profil.age.present? ? "#{@player_profil.age} ans" : "Âge NR" %></strong></p>

      <p><strong>
        <% if @player_profil.date_of_birth.present? %>
          <%= @player_profil.date_of_birth.strftime("%d/%m/%Y")%>
        <% else %>
          Date de naissance NR
        <% end %>
       </strong></p>
      <p><strong><%= @player_profil.weight.present? ? "#{@player_profil.weight} kg" : "Poids NR" %></strong></p>
      <p><strong><%= @player_profil.vma.present? ? "VMA : #{@player_profil.vma}" : "VMA NR" %></strong></p>
      <p><strong><%= @player_profil.job.present? ? @player_profil.job : "Travail NR" %></strong></p>

      <%# if @player_profil.job.present? %>
        <%# <p class="text-center"> %>
          <%# link_to job_load_evaluations_path do %>
            <%# <strong><em>
              <span class="text-dark">Evaluation du travail <i class="fa-solid fa-arrow-up-right-from-square ms-1 text-dark"></i></span>
            </em></strong> %>
          <%# end %>
        <%# </p> %>
      <%# end %>

      <% if @player_profil.children_count.present? %>
        <% if @player_profil.children_count > 1 %>
          <p><strong><%= @player_profil.children_count %> enfants</strong></p>
        <% elsif @player_profil.children_count == 1 %>
          <p><strong>1 enfant</strong></p>
        <% else %>
          <p><strong>Aucun enfant</strong></p>
        <% end %>
      <% else %>
        <p><strong>Enfant(s) NR</strong></p>
      <% end %>
    </div>
  </div>

  <div class="presences">
    <div class="row">
      <div class="col-sm-10 col-md-8 col-lg-6 mx-auto">
        <% if current_user.entraineur? %>
          <% if @player_profil.user.attendances.any? %>
            <table class="table table-striped mt-3">
              <thead>
                <tr>
                  <th>Date de l'entraînement</th>
                  <th>Statut</th>
                </tr>
              </thead>
              <tbody>
                 <% @player_profil.user.attendances.sort_by { |a| a.training.date }.each do |attendance| %>
                  <tr>
                    <td><%= attendance.training.date.strftime("%d/%m/%Y") %></td>
                    <td>
                      <% status = attendance.status %>
                      <% badge_class = case status
                          when "present" then "badge bg-success"
                          when "absent" then "badge bg-danger"
                          when "late" then "badge bg-warning text-dark"
                          when "excused" then "badge bg-info text-dark"
                          else "badge bg-secondary"
                        end %>
                      <span class="<%= badge_class %>"><%= status.capitalize %></span>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p class="text-center"><em></em></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 col-md-10 col-lg-8 mx-auto">
      <% if @player_profil.user.attendances.any? %>
        <div class="total">
          <h4>Statistiques de présence</h4>
          <p><strong>Présent :</strong> <%= @player_profil.user.attendances.present.count %></p>
          <p><strong>Absent :</strong> <%= @player_profil.user.attendances.absent.count %></p>
          <p><strong>En retard :</strong> <%= @player_profil.user.attendances.late.count %></p>
          <p><strong>Excusé :</strong> <%= @player_profil.user.attendances.excused.count %></p>
          <p><strong>Total :</strong> <%= @player_profil.user.attendances.count %></p>
          <p><strong>Ses pénalités :</strong> <%= @player_profil.total_penalties %> absences/retards</p>
          <p><strong>Moyenne de l’équipe :</strong> <%= PlayerProfil.average_penalties %></p>
          <% diff = @player_profil.total_penalties - PlayerProfil.average_penalties %>
          <% if diff > 0 %>
            <p style="color:red;">⬆️ <%= diff %> au-dessus de la moyenne</p>
          <% elsif diff < 0 %>
            <p style="color:green;">⬇️ <%= diff.abs %> en-dessous de la moyenne</p>
          <% else %>
            <p>⚖️ Ce joueur est dans la moyenne</p>
          <% end %>
        </div>
      <% else %>
        <p class="text-center"><em>Aucune donnée disponible pour le moment</em></p>
      <% end %>
    </div>
  </div>

  <%# <div class="montant-penalites">
    <div class="row">
      <div class="col-sm-10 col-md-10 col-lg-8 mx-auto">
        <div class="total">
          <h4>Pénalités</h4> %>
          <%# if @player_profil.total_penalties.to_i > 0 %>
            <%# <p><strong>Nombre de pénalités :</strong> <%= @player_profil.total_penalties</p> %>
            <%# <p><strong>Total à soustraire en fin de saison :</strong> <%= @player_profil.total_penalties_amount €</p> %>
          <%# else %>
            <%# <p class="text-center"><em class="text-dark">Aucune donnée disponible pour le moment</em></p> %>
          <%# end %>
        <%# </div>
      </div>
    </div>
  </div> %>

  <div class="fixed-bottom text-center mb-3">
    <%= link_to "Retour", root_path, class: "btn btn-secondary" %>
  </div>
</div>