config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :exports, only: [:index] do
      collection do
        get :attendances
      end
    end
  end


  resources :attendances do
  collection do
    post :bulk_update
  end
end




  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'pages#home'
  resources :trainings do
    resources :attendances, only: [:index, :show, :new, :create, :update, :edit]
    resources :pre_training_evaluations, only: [:index, :show, :new, :create]
    resources :after_training_evaluations, only: [:index, :show, :new, :create]
  end
  resources :player_profils
  # resources :users do
  #   resources :job_load_evaluations, only: [:new, :create, :show]
  # end
  resources :job_load_evaluations, only: [:index, :show, :new, :create]
  resources :match_performances, only: [:index, :show, :new, :create, :update, :edit]
  # config/routes.rb
  devise_scope :user do
    get   'user/edit_avatar',   to: 'users/registrations#edit_avatar',   as: :edit_avatar_user
    patch 'user/update_avatar', to: 'users/registrations#update_avatar', as: :update_avatar_user
  end

end

app/models/job_load_evaluation.rb
# © 2025 Violaine Soulas Tous droits réservés.
#  Propriété exclusive de Violaine Soulas.
#  Toute reproduction, même partielle, est interdite sans l'autorisation écrite de Violaine Soulas.
class JobLoadEvaluation < ApplicationRecord
  belongs_to :user
end

app/controllers/job_load_evaluations_controller.rb
# © 2025 Violaine Soulas Tous droits réservés.
#  Propriété exclusive de Violaine Soulas.
#  Toute reproduction, même partielle, est interdite sans l'autorisation écrite de Violaine Soulas.
class JobLoadEvaluationsController < ApplicationController
  before_action :set_job_load_evaluation, only: [:show]
  before_action :authenticate_user!
  after_action :verify_policy_scoped, only: :index  # Vérifie la politique du scope pour l'index

  def index

      @player_profils = PlayerProfil.all
      @job_load_evaluations = policy_scope(JobLoadEvaluation).includes(user: :player_profil) # Évite les requêtes N+1


end

  def show
    authorize @job_load_evaluation
  end

  def new
    @job_load_evaluation = JobLoadEvaluation.new
    @player_profils = PlayerProfil.all
    authorize @job_load_evaluation
  end
  def create
    @job_load_evaluation = JobLoadEvaluation.new(job_load_evaluation_params)
    authorize @job_load_evaluation

    # Associe l'évaluation de charge de travail à l'utilisateur actuel ou à un joueur spécifique
    @job_load_evaluation.user = if current_user.entraineur?
                                  User.find(job_load_evaluation_params[:user_id]) # Associe le joueur sélectionné par l'entraîneur
                                else
                                  current_user # Si c'est le joueur lui-même, on utilise l'utilisateur connecté
                                end

    if @job_load_evaluation.save
      redirect_to @job_load_evaluation, notice: 'L’évaluation a été créée avec succès.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def job_load_evaluation_params
    params.require(:job_load_evaluation).permit(:period, :rating, :user_id)
  end

  def set_job_load_evaluation
    @job_load_evaluation = JobLoadEvaluation.find(params[:id])
  end
end

app/views/job_load_evaluations/index.html.erb
<div class="container mt-5">
  <h1 class="text-center">Évaluations de pénibilité de l'activité professionnelle</h1>

  <% if current_user.entraineur? %>
    <div class="text-end my-4">
    <%= link_to "Nouvelle évaluation", new_job_load_evaluation_path, class: "btn-add text-white" %>
  </div>
  <% end %>
<% if @job_load_evaluations.present? %>
  <table class="table">
    <thead>
      <tr>
        <% if current_user.entraineur? %>
          <th>Joueur</th>
        <% end %>
        <th>Période</th>
        <th>Note</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @job_load_evaluations.each do |evaluation| %>
        <tr>
          <% if current_user.entraineur? %>
            <td><%= evaluation.user.player_profil&.first_name %> <%= evaluation.user.player_profil&.last_name %></td>
          <% end %>
          <td><%= evaluation.period %></td>
          <td><%= evaluation.rating %></td>
          <td>
            <%= link_to "Voir", job_load_evaluation_path(evaluation), class: "btn btn-sm btn-primary text-white" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <p class="text-center">Pas de données pour le moment</p>
<% end %>

  <div class="my-3">
    <%= link_to "Retour", root_path, class: "btn btn-secondary text-white mt-3" %>
</div>
</div>

app/views/job_load_evaluations/new.html.erb
<div class="container mt-5">
  <h2 class="text-center">Nouvelle évaluation de pénibilité de l'activité professionnelle</h2>
  <div class="form-job-load-evaluation mt-3">
    <div class="row d-flex justify-content-center">
      <div class="col-6 col-sm-4 col-md-4 col-lg-4 ">
        <%= simple_form_for @job_load_evaluation do |f| %>

          <!-- Sélection du joueur (uniquement pour l'entraîneur) -->
          <% if current_user.entraineur? %>
            <div class="form-group mt-4">
              <%= f.label :user_id, "Joueur" %>
              <%= f.select :user_id,
                  @player_profils.map { |p| ["#{p.first_name} #{p.last_name}", p.user_id] },
                  { include_blank: "Sélectionner un joueur" },
                  class: "form-control" %>
            </div>
          <% end %>

          <!-- Période et note -->
          <%= f.input :period, label: "Période", class: "form-control" %>
          <%= f.input :rating, label: "Note", class: "form-control" %>

          <!-- Bouton de soumission -->
          <%= f.button :submit, "Créer", class: "btn btn-primary mt-3" %>

        <% end %>
      </div>
    </div>
  </div>

  <!-- Lien de retour -->
  <div class="text-start mt-3">
    <%= link_to "Retour", job_load_evaluations_path, class: "btn btn-secondary text-white mt-3" %>
  </div>
</div>

app/views/job_load_evaluations/show.html.erb
<div class="container mt-5">
  <h1 class="mb-3">Détail de l’évaluation</h1>
  <div class="row">
    <div class="col-sm-10 col-md-8 col-lg-6 mx-auto">
      <div class="details-eval mt-3">
      <% if current_user.entraineur? %>
        <p class="text-dark"><strong>Joueur :</strong> <%= @job_load_evaluation.user.player_profil&.first_name %> <%= @job_load_evaluation.user.player_profil&.last_name %></p>
      <% end %>
      <p class="text-dark" ><strong>Période :</strong> <%= @job_load_evaluation.period %></p>
      <p class="text-dark"><strong>Note de charge :</strong> <%= @job_load_evaluation.rating %> / 5</p>
    </div>
  </div>

  </div>



  <%= link_to "Retour", job_load_evaluations_path, class: "btn btn-secondary text-white mt-3" %>
</div>